# edit application name
app_name: 'ShakeConverter2'
# edit provisioning profile name
provisioning_profile: 'SoftShakeDemo'

ci_folder: '.'

server: '10.28.0.38'
user: 'valtech'
ssh_path: 'SoftwareFactory/ssh/id_rsa_valtech_mobile_store'
www_path: '/var/www/'
sign: 'iPhone Developer'
users: 'iPad de Valtech'
